# References: https://www.cloudways.com/blog/php-continuous-integration-travis-ci/
# References: https://docs.travis-ci.com/user/notifications/
# References: https://gist.github.com/gilbitron/5cac0ac5fa07e9b354ac
# References: https://docs.travis-ci.com/user/sonarcloud/

dist: trusty

language: php

php:
- 7.2.10

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install

addons:
  sonarcloud:
    organization: dejongyeong-github
    token:
      secure: "MFTj8c6fheT7q1ePQ3XyGpTh//VOWmMgFKI5oaWqGssPt9RcIxpXPyYkVew2jEcE4w6+hV5Mk95uQ6cZpQRVgPIsbvMCcnUku/KnoZK53w7SltlJAWhQ6hzsYE2PdRoCXZiAHh+1bQA22/wh2+S+QmpQJ/InmrTFBEwZAvIZs6ascLYi024y1OnX7ZpNTJhfcPRfEW4Rp/jK4L+44VqLSv0yXngNYY+5M48vv7NRedGNs64JZeGdPtj4BYlW6wyCl8w1hzHqbbeK+5oRbtp1KSXAAwBGkdFpdGRoSTWvJart8q3txdBNKCmuTW4/8i6zvzEx6YO2k0WvyYBPHTMvsAvXPf+S0KoHewK0TWtqcyMlUelQ7fa5PWa6JlSsPSrJjbKY6il4ok1UZIIf8KYhmFJKTL7Iiu1+hlYasxTW/F9E/oXgGcQBahE6T9lexHfx8UtXNNb+m5c962zDJK5Fw8YQ5G1j/olTIQGOIbs1N/5D50MIP3PSGyZ6EHVEQ7MVKbhnSKYzEJfwdxBurKmNwGjakFWIGxOa1HREIgNuExLERdx+oE6i0aOojda0pg1nUvGQ4nwxmIq/UguNlLIUSJMFSI5WmXEt6iSlYGQhdI9Xup0ZYdc//u6T4yBfs9aXN2anvusZNR+vYeZbftdDpXgzJmyf2H9HNHtIGfc29zA="

script:
  - php artisan key:generate
  - php artisan passport:install
  - php artisan migrate
  - vendor/bin/phpunit
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: "sTw6fXtv45GcE9daQWtdyKbrMOYzbj/LEL8nlMXghTDiXbOfEFwLAg2f/0DvreBZf3RwRAV8BnHuvs0nR85E/NfYWJKR+qGDyvs5M25BRIIW5/xoOlAFcda1fVjhVNjRkEwr9L8uuPRbWYsEWjr7UsZd6gDi7Wn06umuGf7JGH/QUVzylXXGqqiy4+V4vXsGIcV/wAIg6VPPS5HwECF6p7X5hv6MwRS27JBlbnhz2zA7dDsFx8b1IsqAlVuDMASfnKQALs+PzIhVbVZyljmIEwzUldLQImoOPkv0gZeWMnXNZcV1EH6JYOIuiX4lTCJGLoGw1EFAq6FnKD/cW0UqiQC057IoFk41f1pS2B6mrPid79L525a2J6E+PYI5bOw2Kq9RkgYHjP0ZflHVYJjFZ8dn10UZU/ebaSHKRU8kwLvwvxkDoDVx7ZOB733D8kykriwm/9G2v1QgRN0SbYgMqLGh0NJCIyNG5+o2NCC87D9baa4SloECOuh88UeDWTTfOQljhuRTkrzTG077lqFE1IJhwYcx/a+l5Fwz2U6iLKkjYCf4cMqiOQMnFgy0Y5jyduwqTzL/fzFl57QmvWSMmKOX+y1wD+RR1vhMwUSegE4T8egOXLSa4suKfAk8q0UVBrFSbo+BPuqer/Qn8rPP6bP2WkH3tQdyRNto4TheGtE="
  on:
    master

matrix:
  fast_finish: true

notifications:
  slack: ittralee:aGvG53DwjXzULD6B07n9Xe8o
  on_success: always
  on_failure: always
