# References: https://www.cloudways.com/blog/php-continuous-integration-travis-ci/
# References: https://docs.travis-ci.com/user/notifications/
# References: https://gist.github.com/gilbitron/5cac0ac5fa07e9b354ac
# References: https://docs.travis-ci.com/user/sonarcloud/

dist: trusty

language: php

cache: bundler

php:
- 7.2.10

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install

addons:
  sonarcloud:
    organization: dejongyeong-github
    token:
      secure: "MFTj8c6fheT7q1ePQ3XyGpTh//VOWmMgFKI5oaWqGssPt9RcIxpXPyYkVew2jEcE4w6+hV5Mk95uQ6cZpQRVgPIsbvMCcnUku/KnoZK53w7SltlJAWhQ6hzsYE2PdRoCXZiAHh+1bQA22/wh2+S+QmpQJ/InmrTFBEwZAvIZs6ascLYi024y1OnX7ZpNTJhfcPRfEW4Rp/jK4L+44VqLSv0yXngNYY+5M48vv7NRedGNs64JZeGdPtj4BYlW6wyCl8w1hzHqbbeK+5oRbtp1KSXAAwBGkdFpdGRoSTWvJart8q3txdBNKCmuTW4/8i6zvzEx6YO2k0WvyYBPHTMvsAvXPf+S0KoHewK0TWtqcyMlUelQ7fa5PWa6JlSsPSrJjbKY6il4ok1UZIIf8KYhmFJKTL7Iiu1+hlYasxTW/F9E/oXgGcQBahE6T9lexHfx8UtXNNb+m5c962zDJK5Fw8YQ5G1j/olTIQGOIbs1N/5D50MIP3PSGyZ6EHVEQ7MVKbhnSKYzEJfwdxBurKmNwGjakFWIGxOa1HREIgNuExLERdx+oE6i0aOojda0pg1nUvGQ4nwxmIq/UguNlLIUSJMFSI5WmXEt6iSlYGQhdI9Xup0ZYdc//u6T4yBfs9aXN2anvusZNR+vYeZbftdDpXgzJmyf2H9HNHtIGfc29zA="

script:
  - php artisan key:generate
  - php artisan passport:install
  - php artisan migrate
  - vendor/bin/phpunit
  - sonar-scanner

deploy:
  provider: heroku
  api_key:
    secure: "iaIq71cBnKBftxguXUz6Us1KpvRiM4LR98VAxe8w7KkhilO6sAK0AuDWh6r2UJV6nOyvPN4ZDvu3Wp24vPw/zHBwxJPuxUXChWnz77NEtvjXaCerEkt1T+59WNx68uSq4UFye37AVr7ngXPkcddsOBsoHFSNuGutNX12b+93hOEh9jLV/zTq7fyCpzuoQr0qwxUFiiOY0xSCUsegjrfAnjTcdRviuHMEj+u9YarEk58nakbT0xYjZNR+oNgdvCxkabuzc4+3JtQEmCaoyRovI2iE49jjKFegcY11tlCy46oN6yGeTz7wHKljmkKXTSPT7pcsLWmc2VtTXGdrSd6TKlgD/L9RMEEk24tY/ixSnJQFvBoLmJtX/Tt8k/L5atj7nh+phNXEYYLcbarJRYUd8R66PF4XUO7sTWsjfN2TkszAKmOX9zNO8K4u6Y2vyfiJCY2qJvKz6cWfuGYcnOIBt8Aq0fkg64NbYf7U5yKDbAl5SiEZmzZyjKdKxnYvhnwQOMCFD+8Hphi4u5bwsM8byvQpRYyidEsR9vUP9Bav3XTCKDHs9VfhDsqUuBPl8JLnjJvObyC6wo8k0GejBGTZwRluTlRXr1Trya7UlzDJKioPTdLh0NmX+Ve+Cq6CSVHeAfsvMQ9OBTj9eqTRXxIYKysEmE0QOGnGG89CR5hjGGs="
  app:
    dev-ops

matrix:
  fast_finish: true

notifications:
  slack: ittralee:aGvG53DwjXzULD6B07n9Xe8o
  on_success: always
  on_failure: always
