# References: https://www.cloudways.com/blog/php-continuous-integration-travis-ci/
# References: https://docs.travis-ci.com/user/notifications/
# References: https://gist.github.com/gilbitron/5cac0ac5fa07e9b354ac
# References: https://docs.travis-ci.com/user/sonarcloud/

dist: trusty

language: php

php:
- 7.2.10

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install

addons:
  sonarcloud:
    organization: dejongyeong-github
    token:
      secure: "MFTj8c6fheT7q1ePQ3XyGpTh//VOWmMgFKI5oaWqGssPt9RcIxpXPyYkVew2jEcE4w6+hV5Mk95uQ6cZpQRVgPIsbvMCcnUku/KnoZK53w7SltlJAWhQ6hzsYE2PdRoCXZiAHh+1bQA22/wh2+S+QmpQJ/InmrTFBEwZAvIZs6ascLYi024y1OnX7ZpNTJhfcPRfEW4Rp/jK4L+44VqLSv0yXngNYY+5M48vv7NRedGNs64JZeGdPtj4BYlW6wyCl8w1hzHqbbeK+5oRbtp1KSXAAwBGkdFpdGRoSTWvJart8q3txdBNKCmuTW4/8i6zvzEx6YO2k0WvyYBPHTMvsAvXPf+S0KoHewK0TWtqcyMlUelQ7fa5PWa6JlSsPSrJjbKY6il4ok1UZIIf8KYhmFJKTL7Iiu1+hlYasxTW/F9E/oXgGcQBahE6T9lexHfx8UtXNNb+m5c962zDJK5Fw8YQ5G1j/olTIQGOIbs1N/5D50MIP3PSGyZ6EHVEQ7MVKbhnSKYzEJfwdxBurKmNwGjakFWIGxOa1HREIgNuExLERdx+oE6i0aOojda0pg1nUvGQ4nwxmIq/UguNlLIUSJMFSI5WmXEt6iSlYGQhdI9Xup0ZYdc//u6T4yBfs9aXN2anvusZNR+vYeZbftdDpXgzJmyf2H9HNHtIGfc29zA="

script:
  - php artisan key:generate
  - php artisan passport:install
  - php artisan migrate
  - vendor/bin/phpunit
  - sonar-scanner

cache:
  directories:
    - $HOME/.composer/cache/files

deploy:
  provider: heroku
  api_key:
    secure: "fFfzlw4Ix5Mw9maZDTO3Rz8NZhWkWMKstAUXHHR6LAtWSzPd1K80pt/MyCnLe+OcEZPoL+RYJvt69RG/LSc6nxhByiHULcJ5ej5jcvLJinLbuN04wxzbzCAvfg6Zv3vKyzrcIDPZvYrbqk3djUDb5JB7EpXxmOD8tQObyrBKok//mdJdSHsDwrDFiiMFUeAGa/GG3h87Cc7UjTyzfYazi8Ws8B3ttsHQtTE3ARWvmMh/8ASfxD4cEpkTpAFQP2nwOkZpzu4jDr5DSXjpYSgQrpMbeGEnqAUEb9j6Vv2sgMt1OpB462AJupdb0az90GFp4RD6PET70Cu1vx51buWp4l6tnekFbN1RC2niNPS76+09OF5/Jjy8mYMZwSWfYYIl/QoFC5aLYGCHAp/7c4YrANh2XQ0TQYRJ8lN2hCTna3tTgoMbHKnhbhtYMfZSoH+DYuYWtNC1UzMimr2Th7jcQajM73hkRB6n61H/lwJdVizI7Y0I4CI0xvIhZe1vJe8uUtp8L+rK/dD5i1/MPB0DS7aVB+IWRGItVNJmo5/RoP0lYU3WoXSLZTTrYFIvqTSzpj2NKIGqx4zUYQb1gL4dPdj2mVEvb50H2eQf7VeZridt49dZchwbyxNFHzY/Zq3k9RngVneaKXnzjVzQEtzYfs7VJOUa3UJE+XIh/bGIWK8="

matrix:
  fast_finish: true

notifications:
  slack: ittralee:aGvG53DwjXzULD6B07n9Xe8o
  on_success: always
  on_failure: always
