# References: https://www.cloudways.com/blog/php-continuous-integration-travis-ci/
# References: https://docs.travis-ci.com/user/notifications/
# References: https://gist.github.com/gilbitron/5cac0ac5fa07e9b354ac
# References: https://docs.travis-ci.com/user/sonarcloud/
# References: https://medium.com/@felipeluizsoares/automatically-deploy-with-travis-ci-and-heroku-ddba1361647f
# References: https://mattstauffer.com/blog/laravel-on-heroku-using-a-postgresql-database/

dist: trusty

language: php

php:
- 7.2.10

before_script:
  - cp .env.travis .env
  - composer self-update
  - composer install --no-interaction
  - npm install

addons:
  sonarcloud:
    organization: dejongyeong-github
    token:
      secure: "MFTj8c6fheT7q1ePQ3XyGpTh//VOWmMgFKI5oaWqGssPt9RcIxpXPyYkVew2jEcE4w6+hV5Mk95uQ6cZpQRVgPIsbvMCcnUku/KnoZK53w7SltlJAWhQ6hzsYE2PdRoCXZiAHh+1bQA22/wh2+S+QmpQJ/InmrTFBEwZAvIZs6ascLYi024y1OnX7ZpNTJhfcPRfEW4Rp/jK4L+44VqLSv0yXngNYY+5M48vv7NRedGNs64JZeGdPtj4BYlW6wyCl8w1hzHqbbeK+5oRbtp1KSXAAwBGkdFpdGRoSTWvJart8q3txdBNKCmuTW4/8i6zvzEx6YO2k0WvyYBPHTMvsAvXPf+S0KoHewK0TWtqcyMlUelQ7fa5PWa6JlSsPSrJjbKY6il4ok1UZIIf8KYhmFJKTL7Iiu1+hlYasxTW/F9E/oXgGcQBahE6T9lexHfx8UtXNNb+m5c962zDJK5Fw8YQ5G1j/olTIQGOIbs1N/5D50MIP3PSGyZ6EHVEQ7MVKbhnSKYzEJfwdxBurKmNwGjakFWIGxOa1HREIgNuExLERdx+oE6i0aOojda0pg1nUvGQ4nwxmIq/UguNlLIUSJMFSI5WmXEt6iSlYGQhdI9Xup0ZYdc//u6T4yBfs9aXN2anvusZNR+vYeZbftdDpXgzJmyf2H9HNHtIGfc29zA="

script:
  - php artisan migrate:refresh --seed --force
  - vendor/bin/phpunit
  - sonar-scanner

cache:
  directories:
    - $HOME/.composer/cache/files

deploy:
  provider: heroku
  api_key:
    secure: "pSp9fArwaamQteWa/QTJ+nqOhqbMwJjGPtydO5bkoqLJtq3tZf9gj82v/uqOQ52LV8UcddXclf+pFRBt2zPVdrn7T8aOuNJqPJRNqavqjljF1Y4N6Ae9S9sSeMsQK7Gm5CPXOrP6nkTy7My0jrkHtWshs3Cd8pMqO46gXyA4X9v30N0OfhH6D6+GZLuX2j0gJOtTaDYq/VbUyvHbZY1YLMT80ZlryKFgtDC2ZNztCjTWlr16DGAgbFgwsUm0ekHZsfexU0gnYj9cLyalUO7HoBU4ylsLZg1+udLRbMknEQ1fyW7DWcn3faiuCvT4bAMpcrQIVV/VGRyF/cPEGmEl4JHt8ro0L4r85w1ckA/ERXHdRaSANtE1hW6cOmluPGxu6Sa5tYyYsiITHjea0oY8sXXHEI7K8u6TjytpTEdTgYO+C9qQQABoH4j3mg8fo3AqyQ/LwazEGtXY1aafnUjdErtuVNJsnS/G61vUaQfxd3VOmq7wsWASqVMwy9kZNSIxGnOZoikPyVAtzQjJXxiO16qToaM9dBqsM+aDIPE90O2CfZG2+YgizrlWEgC2JjpSTJXaSox0PxOi1BbpH3u+8Fvts+Ru4Vk/k9mIi4Q9d8/K1nrPphkwfKaJuJEydTUevYnE5opnfneb/LIY63ye/2fD6i0Ha/7iqeWpAcCLKbA="
  app: laravel-store-app
  on:
    repo: dejongyeong/dev-ops

matrix:
  fast_finish: true

notifications:
  slack: ittralee:aGvG53DwjXzULD6B07n9Xe8o
  on_success: always
  on_failure: always
